### ISSUE TITLE
Error message, when I install OpenCATS to my Synology NAS

### ISSUE THREAD

**Issue by ichris007** [opencats/OpenCATS_Documentation#14]
I have installed the MariaDB 10 in my Synology NAS, but when I use the installwizard.php to test, there is error message below:
---------------------------------------------------
PHP MySQL extension (mysql) is not loaded.
Check your settings in php.ini.

Under certain Linux / BSD distributions, the PHP MySQL extension is a separate package.

Debian: Run "apt-get install php5-mysql" and restart your webserver.

FreeBSD: Install the php5-mysql port, or configure MySQL support in the php-extensions port and restart your webserver.
---------------------------------------------------
Who can give me some suggestion for resolve it?
Thx.

**Comment by RussH** [comment]
I assume this is still referring to CandidATS?

**Comment by ichris007** [comment]
@RussH Not refer to  CandidATS, this is what I meet during the installing of  OpenCATS.

**Comment by RussH** [comment]
Hi @ichris007 you've probably pulled in a current PHP v7, the current released version does not support PHP v7 - please use a version of PHP that OpenCATS supports..

**Comment by ichris007** [comment]
@RussH Ok, I will try as your suggest.
