### ISSUE TITLE
pdf or doc files do not work using massimport

### ISSUE THREAD

**Issue by makavelli12** [opencats/OpenCATS_Documentation#18]
Am able to massimport docx files. but not .pdf or .doc files. These have to be added manually one by one.

I am running OpenCATS on hosting service and otherwise works fine.

Hope you can advise.

Thanks,

Mak

**Comment by RussH** [comment]
Hi @makavelli12 this is just the github repo for the opencats documentation - happy to support you but it's probably best suited to the user forums at forums.opencats.org. I'll help you out there! If you can check that you have pdf2txt installed etc we can take it from there.
