### ISSUE TITLE
Issue installing opencats on shared hosting opencats : Error 404 page is lost

### ISSUE THREAD

**Issue by nalliancetech** [opencats/OpenCATS_Documentation#19]
Can you plesae help

**Comment by shantadam** [comment]
Your request is way too broad. Please shed some more light on:

  *   Your host environment setup. (hosted locally, remote, docker, etc.)
  *   Your employed technology stack versions. (apache, php, mysql, etc.)
  *   What is your level of expertise with servers? (none, novice, intermediate, expert)
  *   Can you SSH into the server?
  *   What is you level of access to the server? (root, etc.)
  *   Which version of OpenCATS you’re using? (latest greatest, older, etc.)
  *   How did you get a hold of OpenCATS? (If github, which branch?, did you download a zip?, etc.)
  *   What are the steps you took till you faced an issue? (describe as much possible step-by-step)
  *   Do you have access to server logs? (apache logs, php logs, mysql logs, etc.)
Thank you.

Regards,
@shantadam

**Comment by shantadam** [comment]
Thank you for your confirmation, Amit.
We’re glad you managed to resolve your blocker.
Enjoy OpenCATS.

Regards,
@shantadam
