### ISSUE TITLE
Windows Download Not Found

### ISSUE THREAD

**Issue by crankyfire** [opencats/OpenCATS_Documentation#20]
I'm getting a Not Found error when I try to download opencats-09.9.4-full.zip, while I'm following your install for Windows Documentation. 

The documentation I'm following is:
https://github.com/opencats/OpenCATS_Documentation/blob/master/docs/install-windows.rst

**Comment by RussH** [comment]
Hi Mitchell, we're currently testing out 0.9.5 for php 7.x compatibility, otherwise older releases support only php 5.6 

https://github.com/opencats/OpenCATS/releases
