### ISSUE TITLE
Update documentation about the move to MPL v2

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS_Documentation#3]

**Comment by cptr13** [comment]
So basically, change the license overview in the documentation to reflect this?: https://www.bountysource.com/issues/36391809-update-license

**Comment by RussH** [comment]
Yes! Exactly. Have had some messages today from the forum asking for clarification and realised the documentation was probably out of date.

**Comment by cptr13** [comment]
It's updated.  I'm not sure whether it's what you had in mind.  I changed a few lines at the top.  Look at it whenever you have time and let me know if you want something more immersive.  If you like it I'll close the issue.

**Comment by mlespiau** [comment]
Hi @cptr13 I looked into the docs and they are crystal clear now! Thanks!
