### ISSUE TITLE
Add the '10 minute dev guide to OpenCATS'

### ISSUE THREAD

**Issue by RussH** [opencats/OpenCATS_Documentation#4]
Copied from "10 Minute Guide to CATS Source Code" by CATS Dev Team, Will Buckner.

 We have not used any outside frameworks. CATS framework is very light and conceptually simple to understand. This allows modifications to be isolated, preventing, for example, a small change to a template from affecting library code, or a major change in database structure from requiring a change to every single page.
Let’s have a look at the layout of the code:
CATS is roughly divided into 3 parts:
Modules
Library Components
Templates
Modules
A module is loosely related to the tabs you see in the GUI and consists of the user interface logic and one or more “templates” to render the HTML page.
Some of the modules in CATS are:
Home
Candidates
Contacts
Calendar
etc…
Browse the modules directory to see the all the current modules in CATS. Each module has its own seperate directory.
Library Components
Library components are PHP objects which encapsulate lower-level functionality, such as interfacing with a database, parsing addresses, sending e-mail, etc. For each module, there is roughly corresponding library component (but not all libraries directly correspond to a module).
Examples of some library components are:
Candidates
Search
Users
VCard
AddressParser
…
Browse the lib/ directory to see the all different library components.
CATS Page Request Flow
Every page request to CATS goes through index.php, which acts as a “router” / delegator to the modules.
A page request is sent to index.php
index.php parses the URL and sends the request to the corresponding module (specified by m= in the URL) for further processing
A module parses the “action” (specified by a= in the URL) and invokes the corresponding method within the module.
The method processes the request, often using library components
The function displays a template file, if necessary, and fills in the appropriate data and renders the HTML page
Every CATS page request goes more or less through the above 5 steps.
CATS URLs are designed to be intuitive and easy to use for developers:
E.g. http://catsone.net/index.php?m=clients&a=show&clientID=239
means:
m = clients
a = show
clientID = 329
index.php sends the URL to the “clients” module. The clients module processes the action “show” for clientID 329. We want to display details of client 239.
Here is the basic layout of a module:
/* mymodule/MyModuleUI.php: */
class MyModuleUI extends UserInterface
{
    public function __construct()
    {
        parent::__construct();
        $this->_moduleDirectory = ‘mymodule’;
    }
    public function handleRequest()
    {
        $action = $this->getAction();
        switch ($action)
        {
            case ‘myAction’:
                $this->myAction();
                break;
            …
        }
    }

    public function myAction()
    {
        …
    }
}
Templates
Modules, as mentioned above, contain the necessary code to render the HTML pages in CATS. HTML is separated from the rest of the code via “templates”. A page is displayed by a template by assigning variables to it using assign() and then call it’s display() method.

public function myAction()
{
    …

    $this->_template->assign(‘myVariable’, $myValue);
    $this->_template->display(‘./modules/mymodule/MyTemplate.tpl’);
}
To display a variable inside a template, use:
<?php $this->_($this->myVariable); ?>
Interfacing with the database is only done at the library level. This limits the effects that a change in the database structure can have on the upper layers of the code.

**Comment by cptr13** [comment]
hrmm, ok.  I'll add it in.  Is this old?

**Comment by RussH** [comment]
Yes it's old, but still useful. Maybe you could post into slack to see any dev comments

**Comment by cptr13** [comment]
I will.  Thanks!

**Comment by cptr13** [comment]
Done....closed!
